# Generated by Django 4.2.7 on 2023-11-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='advertiser',
        ),
        migrations.AddField(
            model_name='ad',
            name='ads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.advertiser'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
