# Generated by Django 4.2.7 on 2023-11-24 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_remove_ad_advertiser_ad_ads_advertiser_clicks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ads',
        ),
        migrations.AddField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='advertiser_management.advertiser'),
        ),
    ]
