# Generated by Django 4.2.7 on 2023-11-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_remove_ad_clicks_remove_ad_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='ad',
        ),
        migrations.AddField(
            model_name='ad',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Click',
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
