# Generated by Django 4.2.7 on 2023-11-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_view_click'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='views',
        ),
    ]
