# Generated by Django 4.2.7 on 2023-11-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0010_ad_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='advertiser_management.advertiser'),
        ),
        migrations.AlterField(
            model_name='click',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad'),
        ),
        migrations.AlterField(
            model_name='view',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad'),
        ),
    ]
