# Generated by Django 4.2.7 on 2023-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0011_alter_ad_advertiser_alter_click_ad_alter_view_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='view',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
