# Generated by Django 4.2.7 on 2023-12-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0012_alter_click_ip_alter_view_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClicksAndViewsPerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks_count', models.PositiveIntegerField()),
                ('views_count', models.PositiveIntegerField()),
                ('time', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='click',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
