# Generated by Django 4.2.7 on 2023-12-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0014_adincclicksview_delete_clicksandviewsperhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='click',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='view',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='click',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_click', to='advertiser_management.ad'),
        ),
        migrations.AlterField(
            model_name='view',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_view', to='advertiser_management.ad'),
        ),
        migrations.DeleteModel(
            name='AdIncClicksView',
        ),
    ]
