# Generated by Django 4.2.7 on 2023-12-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0016_remove_ad_click_remove_ad_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
