# Generated by Django 4.2.7 on 2023-12-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0017_alter_click_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='click_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='view_time',
            new_name='created_time',
        ),
    ]
