# Generated by Django 4.2.7 on 2023-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0018_rename_click_time_click_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
